model: DeepSetModel
output: ./output/deepset32_fj
run_config:
  plotting: True
  logger: True
  verbose: True # 0 = silent, 1 = info, 2 = debug
model_config:
  # expected number of input features per particle
  n_features: 24
  # number of output classes
  n_classes: 4
  # conv layers applied per particle (1x conv)
  conv1d_layers: [32, 32, 32]
  classification_layers: [32]
  aggregator: mean
  #eval_metrics: [accuracy, f1_score]
quantization_config: {}
training_config:
  epochs: 1000
  optimizer: adam
  optimizer_params:
    lr: 0.0032
  scheduler: reduce_on_plateau
  scheduler_params:
    mode: min
    factor: 0.1
    patience: 5
    min_lr: 1e-6
  callbacks:
      EarlyStopping:
        monitor: val_loss
        patience: 10
      ModelCheckpoint:
        monitor: val_loss
        save_best_only: true
  metrics:
      - accuracy:
          name: accuracy
      - accuracy:
          name: accuracy_per_class
          return_per_class: True
      - auroc:
      - confusion_matrix:
data_config:
  np_data: False
  data_path: ./training_data
  percentage: 50
  batch_size: 128
  validation_split: 0.2
  n_particles: 32
  fields: [pt, etarel, phirel] 
  #fields: [px, py, pz, e] # 4 vec
  target_labels: ['bb', 'cc', 'qq', 'qcd']
  balance_classes: True 

hls4ml_config: {}