model: ParticleTransformer
output: ./output/particle_transformer_kin_7class
run_config:
  debug: False
  plotting: True
  logger: True
  verbose: 1
model_config:
  # input feature sizes (pf = particle-flow)
  input_dim: 4
  pf_input_dim: 7
  # number of output classes
  n_classes: 7

  # Pairwise / architecture settings
  pair_input_dim: 4
  pair_extra_dim: 0
  remove_self_pair: False
  use_pre_activation_pair: False
  embed_dims: [128, 512, 128]
  pair_embed_dims: [64, 64, 64]
  num_heads: 8
  num_layers: 8
  num_cls_layers: 2
  # fully-connected head: list of [out_dim, dropout_rate] tuples
  # The implementation will append the final linear to `n_classes` automatically.
  fc_params: [[128, 0.2], [64, 0.2]]

  activation: gelu
  trim: True
  for_inference: False
  use_amp: False
  #from_pretrained: True
  #ckpt_path: ./pre-trained/ParticleTransformer/ParT_kin.pt
  #fine_tune: True
  features: "kin" # "full"=17 f, "kinpid" = 13 f or "kin" = 7 f

quantization_config: {}
training_config:
  epochs: 100
  log_interval: 1000
  optimizer: adamw
  optimizer_params:
    lr: 1e-3
    weight_decay: 0.01
  loss: cross_entropy
  #scheduler: cosine_with_warmup
  #scheduler_params:
  #  warmup_steps: 10
  #  eta_min: 1e-5
  scheduler: "reduce_on_plateau"
  scheduler_params:
    mode: min
    factor: 0.5
    patience: 3
    min_lr: 1e-6
  callbacks:
      EarlyStopping:
        monitor: val_loss
        patience: 10
      ModelCheckpoint:
        monitor: val_loss
        save_best_only: true
  metrics:
      - accuracy:
      - auroc:
      - confusion_matrix:

data_config:
  data_path: ./training_data
  percentage: 100
  batch_size: 512
  validation_split: 0.2
  n_particles: 32
  shuffle_constits: True
  target_labels: 
  - "ev" # [Top_XXXev]
  - "mv" # [Top_XXXmv]
  - "H_gg" #
  - "H_bb" #
  - "H_mm" #
  - "H_ee" #
  #- "H_cc" #
  - "QCD_others"



  balance_classes: True
  #transform: True

hls4ml_config: {}
