model: ParticleTransformer
output: ./output/particle_transformer
run_config:
  debug: False
  plotting: True
  logger: True
  verbose: True
model_config:
  # input feature sizes (pf = particle-flow)
  input_dim: 4
  pf_input_dim: 7
  # number of output classes
  n_classes: 5

  # Pairwise / architecture settings
  pair_input_dim: 4
  pair_extra_dim: 0
  remove_self_pair: False
  use_pre_activation_pair: False
  embed_dims: [128, 512, 128]
  pair_embed_dims: [64, 64, 64]
  num_heads: 8
  num_layers: 8
  num_cls_layers: 2
  # fully-connected head: list of [out_dim, dropout_rate] tuples
  # The implementation will append the final linear to `n_classes` automatically.
  from_pretrained: True
  ckpt_path: ./pre-trained/ParticleTransformer/ParT_kin.pt
  #fine_tune: True
  #modules_to_train: ["fc"]
  fc_params: [[128, 0.1], [64, 0.1]]
  features: "kin" # "full"=17 f, "kinpid" = 13 f or "kin" = 7 f

  activation: gelu
  trim: True
  for_inference: False
  use_amp: False
  #use_masks: False

quantization_config: {}
training_config:
  epochs: 100
  optimizer: adamw
  optimizer_params:
    lr: 1e-4
    weight_decay: 0.01
  loss: cross_entropy
  scheduler: "cosine"
  scheduler_params:
    eta_min: 1e-6
    T_max: 100
  callbacks:
      EarlyStopping:
        monitor: val_loss
        patience: 15
      ModelCheckpoint:
        monitor: val_loss
        save_best_only: true
  metrics:
      - accuracy:
      - auroc:
      - confusion_matrix:



data_config:
  dataset: hls4ml
  np_data: true
  data_path: ./data/train
  percentage: 100
  batch_size: 128
  validation_split: 0.2
  n_particles: 64
  target_labels: ['g', 'q', 'w', 'z', 't']

hls4ml_config: {}
