model: ParticleTransformer
output: ./output/particle_transformer_full_v2
run_config:
  debug: False
  plotting: True
  logger: True
model_config:
  # input feature sizes (pf = particle-flow)
  input_dim: 4
  pf_input_dim: 20
  # number of output classes
  n_classes: 6

  # Pairwise / architecture settings
  pair_input_dim: 4
  pair_extra_dim: 0
  remove_self_pair: False
  use_pre_activation_pair: False
  embed_dims: [128, 512, 128]
  pair_embed_dims: [64, 64, 64]
  num_heads: 8
  num_layers: 8
  num_cls_layers: 2
  # fully-connected head: list of [out_dim, dropout_rate] tuples
  # The implementation will append the final linear to `n_classes` automatically.
  #fc_params: [[128, 0.2], [64, 0.2]]

  activation: gelu
  trim: True
  for_inference: False
  use_amp: False
  #from_pretrained: True
  #ckpt_path: ./pre-trained/ParticleTransformer/ParT_kinpid.pt
  #fine_tune: True
  features: "kin" # "full"=17 f, "kinpid" = 13 f or "kin" = 7 f

quantization_config: {}
training_config:
  epochs: 200
  log_interval: 500
  optimizer: adam
  optimizer_params:
    lr: 1e-3
    weight_decay: 1e-5
  loss: cross_entropy
  #scheduler: cosine_with_warmup
  #scheduler_params:
  #  warmup_steps: 5
  #  eta_min: 1e-6
  scheduler: "reduce_on_plateau"
  scheduler_params:
    mode: min
    factor: 0.5
    patience: 3
    min_lr: 1e-6
  early_stopping:
    patience: 10

data_config:
  np_data: False
  data_path: ./training_data
  percentage: 100
  batch_size: 1024
  validation_split: 0.2
  n_particles: 32
  shuffle_constits: False
  target_labels: ["H_qq", "H_cc", "H_bb", "QCD_others"]
  balance_classes: True
  #transform: True

hls4ml_config: {}
